version: '3'

services:
  proxy-server:
    image: traefik:v2.10
    command:
      --configFile=/traefik.yml
      --api.insecure=true
      --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "7001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/
      - ${CERT_FILE_PATH}:/fullchain.pem
      - ${KEY_FILE_PATH}:/privkey.pem