# traefik.yml

# Enable the Dashboard and API
api:
  dashboard: true
  insecure: true

# Define the entry points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Enable the Docker provider
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    filename: "/serverlist.yml"
    watch: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/fullchain.pem"
        keyFile: "/privkey.pem"

certificatesResolvers:
  letsencrypt:
    acme:
      email: help@mulmuri.dev
      storage: /acme.json
      httpChallenge:
        entryPoint: web